### ISSUE TITLE
Add support for Falcon

### ISSUE THREAD

**Issue by VGFP** [huggingface/optimum-neuron#100]
When trying to export falcon-7b to neuron I am getting an error "KeyError: "refinedwebmodel is not supported yet."
Please add support for Falcon models

**Comment by michaelbenayoun** [comment]
Hi, 
This is planned, but we are waiting for it to be added in Transformers first.

**Comment by gpravi** [comment]
Hi, Is there any update on this?

**Comment by michaelbenayoun** [comment]
The Falcon model will be supported at the next Transformer release. Will add support for this release!
