### ISSUE TITLE
Persistent Cache for `notebooks/text-classification/notebook.ipynb`

### ISSUE THREAD

**Issue by dangdana** [huggingface/optimum-neuron#115]
Hi,

I'm trying to run `notebooks/text-classification/notebook.ipynb` .  Each time it runs, it recompiles, using a different `/tmp/` path each time, e.g.
`2023-06-27 17:59:23.000182: INFO ||NCC_WRAPPER||: Compile cache path: /tmp/tmpytdl1fxg`

 I've never actually completed the compile this way.  It may be progressing but very slowly.  After 30+ minutes it has made little progress (below).  Is this expected?

```
  0%|         | 1/1500 [00:11<4:41:45, 11.28s/it]2023-06-27 17:59:23.000182
.....................................  ............    ...
```

To remedy the compile time issue, I tried using Neuron SDK's [persistent cache](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-features/neuron-caching.htm).  With `neuron_parallel_compile`, I see a cache created and populated at e.g. `/var/tmp/neuron-compile-cache/neuronxcc-2.7.0.40+f7c6cf2a3`.  However, for some reason this cache is not leveraged when I run the training.  Furthermore, when I rerun the `neuron_parallel_compile`,  6-8 graphs are always  recompiled and added into the cache.

Is it possible to use the persistent cache with the notebook?  Or otherwise compile and train in a timely way?

**Comment by philschmid** [comment]
Did you make any changes to the notebook? Where are you running the notebook? On the Hugging Face AMI?
