### ISSUE TITLE
Add Support for SDXL

### ISSUE THREAD

**Issue by fafriat** [huggingface/optimum-neuron#148]
Please add support for compiling stabilityai/stable-diffusion-xl-base-0.9 for inf2.

**Comment by gonzachiar** [comment]
I have the same problem. I'm trying to compile the stabilityai/stable-diffusion-xl-base-1.0 with torch-neuronx but the compilation fails with no clear message.

**Comment by JingyaHuang** [comment]
Hey folks, the export and inference support will be added via these two PRs: #203 and #212 .
