### ISSUE TITLE
roberta for q&a compilation fails

### ISSUE THREAD

**Issue by juliensimon** [huggingface/optimum-neuron#15]
torchrun --nproc_per_node 32 run_swag.py --model_name_or_path roberta-base --do_train --do_eval --learning_rate 5e-5 --num_train_epochs 3 --output_dir /tmp/swag_base --per_gpu_eval_batch_size=16 --per_device_train_batch_size=16 --overwrite_output --max_seq_length 512

Full log attached.

**Comment by michaelbenayoun** [comment]
Batch size is too big for a sequence length of 512. 
Try much much smaller. Like batch_size = 2 (at least for tranining, for evaluation you might be able to get bigger than 2).

**Comment by philschmid** [comment]
Can we close this?
