### ISSUE TITLE
Two unrelated nested issues regarding inference with NeuronStableDiffusionPipeline

### ISSUE THREAD

**Issue by oOraph** [huggingface/optimum-neuron#153]
### First issue

When using the latest diffusers library (Diffusers > 0.19.0, after this commit: 27062c3631b7011a5df45782b8e3d01349d1f3e9)

Some attributes are missing in NeuronStableDiffusionPipeline, causing "components" method to fail

Reproduce:

```
from optimum.neuron import NeuronStableDiffusionPipeline
model_id = "stabilityai/stable-diffusion-2-1-base"
input_shapes = {"batch_size": 1, "height": 512, "width": 512}  
import pdb
pdb.set_trace()
stable_diffusion = NeuronStableDiffusionPipeline.from_pretrained(model_id, export=True, **input_shapes)
save_directory = "sd_neuron/"
stable_diffusion.save_pretrained(save_directory)
stable_diffusion('whatever')
```

Error obtained:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    stable_diffusion('horse')
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/modeling_diffusion.py", line 509, in __call__
    return StableDiffusionPipelineMixin.__call__(self, *args, **kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py", line 178, in __call__
    device = self._execution_device
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'NeuronStableDiffusionPipeline' object has no attribute '_execution_device'
```

Workaround patch (not a proper fix, just to expose the cause):

```
diff --git a/optimum/neuron/modeling_diffusion.py b/optimum/neuron/modeling_diffusion.py
index 8967e16..242a780 100644
--- a/optimum/neuron/modeling_diffusion.py
+++ b/optimum/neuron/modeling_diffusion.py
@@ -24,6 +24,7 @@ from tempfile import TemporaryDirectory
 from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union
 
 import torch
+from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker
 from huggingface_hub import snapshot_download
 from transformers import CLIPFeatureExtractor, CLIPTokenizer, PretrainedConfig
 
@@ -73,14 +74,16 @@ class NeuronStableDiffusionPipelineBase(NeuronBaseModel):
         unet: torch.jit._script.ScriptModule,
         vae_encoder: torch.jit._script.ScriptModule,
         vae_decoder: torch.jit._script.ScriptModule,
-        config: Dict[str, Any],
         tokenizer: CLIPTokenizer,
         scheduler: Union[DDIMScheduler, PNDMScheduler, LMSDiscreteScheduler],
         feature_extractor: Optional[CLIPFeatureExtractor] = None,
+        config: Optional[Dict[str, Any]] = {},
         configs: Optional[Dict[str, "PretrainedConfig"]] = None,
         neuron_configs: Optional[Dict[str, "NeuronConfig"]] = None,
         model_save_dir: Optional[Union[str, Path, TemporaryDirectory]] = None,
         model_and_config_save_paths: Optional[Dict[str, Tuple[str, Path]]] = None,
+        safety_checker: StableDiffusionSafetyChecker = None,
+        requires_safety_checker: bool = True,
     ):
         """
         Args:
@@ -141,7 +144,8 @@ class NeuronStableDiffusionPipelineBase(NeuronBaseModel):
         self.tokenizer = tokenizer
         self.scheduler = scheduler
         self.feature_extractor = feature_extractor
-        self.safety_checker = None
+        self.safety_checker = safety_checker
+        self.requires_safety_checker = requires_safety_checker
         sub_models = {
             DIFFUSION_MODEL_TEXT_ENCODER_NAME: self.text_encoder,
             DIFFUSION_MODEL_UNET_NAME: self.unet,
```

### Second issue

Then nested behind, another error regarding tensor invalid shapes:

from what I understand this is related to the fact that when exporting the model to Neuron, we need to freeze the shapes in advance and while exporting the model one assume some options to be deactivated (example: guidance_scale /guidance free classification -> during export it is indirectly assumed to be deactivated in inference this one gets activated and the input shape differs from the exported one multiplied by 2 on tensor dim 0)

Reproduce:

Same script as before after applying the previous patch, the new error appears 

Error obtained:

```
RuntimeError: 
    Incorrect tensor shape at input tensor #0: received 2 4 64 64, expected 1 4 64 64.
    Incorrect tensor shape at input tensor #1: received 2, expected 1.
    Incorrect tensor shape at input tensor #2: received 2 77 1024, expected 1 77 1024.
```

Reason of this shape unconsistency here:

https://github.com/huggingface/optimum-neuron/blob/main/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py#L182

`do_classifier_free_guidance = guidance_scale > 1.0` -> True, guidance_scale is 7.5 by default

Hence the latent shape on dim 0 should be multiplied by 2 if I understand correctly what's here:

https://github.com/huggingface/optimum-neuron/blob/main/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py#L125https://github.com/huggingface/optimum-neuron/blob/main/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py#L125

Workaround (not a fix either, just to prove the point above):

```
diff --git a/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py b/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py
index 831676a..d6311c6 100644
--- a/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py
+++ b/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion.py
@@ -179,7 +180,10 @@ class StableDiffusionPipelineMixin(StableDiffusionPipeline):
         # here `guidance_scale` is defined analog to the guidance weight `w` of equation (2)
         # of the Imagen paper: https://arxiv.org/pdf/2205.11487.pdf . `guidance_scale = 1`
         # corresponds to doing no classifier free guidance.
-        do_classifier_free_guidance = guidance_scale > 1.0
+
+        # do_classifier_free_guidance = guidance_scale > 1.0
+
+        do_classifier_free_guidance = False
 
         # 3. Encode input prompt
         text_encoder_lora_scale = (
```

**Comment by JingyaHuang** [comment]
Thank you both for the feedback @oOraph @philschmid, and especially those details on the errors @oOraph !

The first issue, it seems to come from recent changes in diffusers. I will just remove device related code from our custom pipeline, which is useless in our case.

And for the second issue, we need to set the `do_classifier_free_guidance=False` or turn on the flag `--dynamic-batch-size` during the export. I will try to optimize that and avoid this occurring.

You can track the patch in this PR: #156. Could you try it out?

**Comment by oOraph** [comment]
Hey @JingyaHuang :), I tried the patch, I can confirm the reported issues are now fixed and inference is working on Inferentia2

But this raises a new question:

Default guidance scale is set to 7.5, meaning that when we perform diffusion inference on a GPU, do_classifier_free_guidance ends up at True

Setting this parameter to True seems to lead to better image generated: closer to the prompt and better image quality (I did not measure it through any clip or fid scores though to prove it, just repeated the operation several times and "looked" at the generated to get this impress). But for Inferentia, it ends up at False for default parameters. So, may be we should enable dynamic batch size at export for Inferentia by default and provide a way to disable it, otherwise images generated with inf2 with default params will have a lower quality than those generated with GPUs.  What do you think ?

**Comment by JingyaHuang** [comment]
@oOraph Have you tried disabling the dynamic batch size but running with two neuon cores by passing `device_ids=[0, 1]`?

Under that case, even when we do not enable the dynamic batching while compiling, `latent_model_input` with doubled batch size will be run on two neuron cores, each one with the input of batch size 1. So I wonder would it be better to disable the dynamic batching by default but using two neuron cores by default.

**Comment by oOraph** [comment]
@JingyaHuang  indeed, if I understand correctly what you said above here is what I did:
1. Reuse my model compiled with dynamic batch size to false
2. Replace the patched line:
```
do_classifier_free_guidance = guidance_scale > 1.0 and self.dynamic_batch_size
```
with the original condition
```
do_classifier_free_guidance = guidance_scale > 1.0
```
Run inference by specifying the two neuron as device ids

-> If I do so, I can also confirm inference works and we get back to the do_classifier_free_guidance True case with the best image quality
-> so you're right, using two neurons by default could also be an option

**Comment by JingyaHuang** [comment]
The issue should solved now, although for those default value I need to make a PR to make it more new-user-friendly. I will close this, feel free to reopen it.
