### ISSUE TITLE
Dimension mismatch in T5LayerNorm with T5ParallelEmbedding

### ISSUE THREAD

**Issue by bocchris-aws** [huggingface/optimum-neuron#170]
After fixing #163 and #169 locally and testing tensor parallel degree=2 for `google/flan-T5-small` and the summarization example, I run into a shape mismatch at the last multiplication in the [T5LayerNorm](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L261) 

where `self.weight.shape = [512]` which is fine but
 `hidden_states.shape = [BS, SEQ_LENGTH, ->2048<-]`. 

This happens at the first attention block where the dimension of `hidden_states` comes directly from the embedding layer (we expect the last dim of it to be `512` (`d_model`)). I therefore hypothesise that there is an issue with the implementation of the ParallelEmbedding.

**Comment by bocchris-aws** [comment]
@michaelbenayoun any updates on this? Can you confirm the bug?

**Comment by michaelbenayoun** [comment]
Hi @bocchris-aws,
I am currently working on fixing the numerous bugs you reported on T5. But I do not manage to reproduce this one (I got OOM before reaching what you are mentioning...), do you have a command to reproduce the issue?

**Comment by bocchris-aws** [comment]
Great! So, given this script:
```
NUM_WORKERS=2
TP=2
BATCH_SIZE=1
T5_SIZE=$1

export XLA_USE_BF16=1
neuron_parallel_compile torchrun --nproc_per_node=$NUM_WORKERS run_summarization.py \
    --model_name_or_path google/flan-t5-$T5_SIZE \
    --do_train \
    --do_eval false \
    --dataset_name cnn_dailymail \
    --dataset_config "3.0.0" \
    --source_prefix "summarize: " \
    --output_dir /tmp/tst-summarization \
    --tensor_parallel_size $TP \
    --per_device_train_batch_size=$BATCH_SIZE \
    --per_device_eval_batch_size=$BATCH_SIZE \
    --overwrite_output_dir
```

The command which should reproduce the error is `./run.sh small`.

**Comment by michaelbenayoun** [comment]
I was not able to reproduce. I have merged a fix for T5 related to an other issue you raised. Can you try from the `main` branch and tell me?

**Comment by bocchris-aws** [comment]
Yup, I am no longer running into this issue.
