### ISSUE TITLE
Invalid target for neuronx-cc on inf2 using trn1 instead of inf2 

### ISSUE THREAD

**Issue by fafriat** [huggingface/optimum-neuron#171]
Hi,
I have remarked the target of neuronx-cc when using NeuronXXX models on inf2 is trn1. I checked that it is compatible to inf2 anyway, but do we lose any optimization using this wrong target ?

**Comment by JingyaHuang** [comment]
Hi @fafriat, what do you mean by "target"? 

`NeuronModelForXXX` classes support inference on both neuron device 1st and 2nd generation. So you can use it on INF2, INF1 and TRN1 instances.  But it's true that some features are only supported on INF2 not INF1.

You can try it out with our showcase examples: https://huggingface.co/docs/optimum-neuron/guides/models. Feel free to reach out if you have any questions.

**Comment by fafriat** [comment]
Hi @JingyaHuang,

When using NeuronModelForXXX, it is automatically compiling for Neuron when export=True,
 In that case, when running on inf2 instance, I have remarked the command triggered from neuronx-cc is using --target trn1 instead of --target inf2...

I know that it is also working on inf2 when target is trn1 but do we lose any  optimization using trn1 instead of inf2 as target ?

**Comment by aws-donkrets** [comment]
Hi @fafriat,
Just noticed this older ticket. The Neuron compiler accepts both the inf2 and trn1 target option-arguments. The ISA between these two instances is similar enough such that the compiler (currently) performs the same optimizations so you are not losing any instance-specific optimizations.  These are defined as separate option-arguments in case, in the future, we identify optimizations that are beneficial specifically for interference or training models. So it is good practice to specify the option-argument based upon the model's purpose.

**Comment by JingyaHuang** [comment]
Close the issue thanks to the answer of @aws-donkrets. Please feel free to re-open if there is any further questions.
