### ISSUE TITLE
Support for Llama2

### ISSUE THREAD

**Issue by samir-souza** [huggingface/optimum-neuron#205]
Now that [NeuronSDK 1.13](https://github.com/aws-neuron/aws-neuron-sdk/releases/tag/v2.13.0) is out and LLama2 is supported for inference, please add support for this model to Optimum Neuron.
Sample: https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/meta-llama-2-13b-sampling.ipynb

This is the most popular/demanded model at the moment. Thanks!

**Comment by josephpconley** [comment]
Does #211 solve this issue?  Do we have any documented tutorials yet (don't see any on the linked docs in the PR).  Thanks!

**Comment by samir-souza** [comment]
Supported added to version 0.0.11+
