### ISSUE TITLE
Make compilation files created by `neuron_parallel_compile` when used in real training.

### ISSUE THREAD

**Issue by michaelbenayoun** [huggingface/optimum-neuron#215]
As per title.

**Comment by 5cp** [comment]
Additional context - for multi-node training with neuronx-nemo-megatron and neuronx-distributed, precompilation with neuron_parallel_compile is required (JiT compilation is not sufficient in these cases).

This enhancement will be required for larger models where multi-node will be the required setup.

**Comment by michaelbenayoun** [comment]
Closing since this is available now.
