### ISSUE TITLE
Exporting on Inf1 vs. Inf2

### ISSUE THREAD

**Issue by boing102** [huggingface/optimum-neuron#237]
Hey,

This might be a silly question, but I want to double check. To export a model for inference on the Inf2 instance type, do I have to run the export script on Inf2 instance type or it can be Inf1 instance?

Thank you.

**Comment by JingyaHuang** [comment]
Hi @boing102, the compilation is processed on CPU, so if you don't want to compile your model on an inf2 instance, you can just use an instance with CPUs. 

p.s if you are using the CLI, you might want to turn off the validation(inference) with `--disable-validation`.

More reading here:https://github.com/huggingface/optimum-neuron/issues/142#issuecomment-1684112249

**Comment by boing102** [comment]
Hi. Thanks for the quick response. So the model compilation/exporting from HF to Neuron doesn't have to happen on an instance with the Inferentia accelerator?

**Comment by JingyaHuang** [comment]
Closing the issue, feel free you reopen if there is any other further questions.
