### ISSUE TITLE
'str' object has no attribute 'name' in TrainerCallback

### ISSUE THREAD

**Issue by bocchris-aws** [huggingface/optimum-neuron#241]
On the current main branch, I get an `AttributeError: 'str' object has no attribute 'name'` error from [here](https://github.com/huggingface/optimum-neuron/blob/main/optimum/neuron/trainer_callback.py#L111) when trying to run the `run_summarization.py` script.

**Comment by michaelbenayoun** [comment]
Please re-open if the issue appears again.
