### ISSUE TITLE
Tensor parallelism: saved model can't be loaded

### ISSUE THREAD

**Issue by bocchris-aws** [huggingface/optimum-neuron#249]
After running finetuning using `run_summarization.py` for a couple of steps, the directory to which the model shards have been saved does not contain a `config.json`. Hence, the model stored can't be loaded using `from_pretrained()`:`
```
OSError: PATH_TO_SAVED_MODEL_DIR does not appear to have a file named config.json.
```
Should the `config.json` be saved together with the shards?

**Comment by michaelbenayoun** [comment]
You need to provide the parent directory instead. The parent directory contains all the config files.
