### ISSUE TITLE
Inference pipeline for text-generation

### ISSUE THREAD

**Issue by evanbrociner** [huggingface/optimum-neuron#252]
Hi. I just wanted to check to see if text-generation is something that will be added to the inference pipeline. Thank you!

**Comment by JingyaHuang** [comment]
Gently pinging @dacorvo for some inputs.

**Comment by dacorvo** [comment]
The feature will be added when we have integrated the next version of AWS Neuron SDK (probably next week): for now only the `gpt2` model can be serialized, leading to long compilation times on every pipeline instantiation for `llama` models.

**Comment by evanbrociner** [comment]
Thank you @JingyaHuang and @dacorvo! Looking forward to it
