### ISSUE TITLE
Loss & metric discrepancy with `predict_with_generate`

### ISSUE THREAD

**Issue by bocchris-aws** [huggingface/optimum-neuron#255]
When we use `predict_with_generate` with `run_summarization.py`, we observe a different evaluation loss than without. Precision seem not to influence the outcome. Command
```
torchrun --nproc_per_node=1 --nnodes=1 run_summarization.py \
    --model_name_or_path t5-small \
    --dataset_name cnn_dailymail \
    --dataset_config "3.0.0" \
    --do_train false \
    --save_strategy no \
    --do_eval \
    --max_eval_samples 64 \
    --max_source_length 512\
    --max_target_length 64 \
    --val_max_target_length 64 \
    --per_device_eval_batch_size 1 \
    --pad_to_max_length \
    --overwrite_output_dir \
    --seed 42 \
    --bf16 \
    --logging_first_step true \
    --source_prefix "summarize: " \
    --tensor_parallel_size 1
```

### TP=1, num workers=1
* `eval_loss` without `predict_with_generate` TRN: 2.4681
* `eval_loss` with `predict_with_generate` TRN: **6.1191**
* `eval_loss` without `predict_with_generate` GPU: 2.374
* `eval_loss` with `predict_with_generate` GPU: 2.4809
* `rougeL` GPU: 22.6228
* `rougeL` TRN: 22.766

### TP=2, num workers=2
* `eval_loss` without `predict_with_generate` TRN: **10.5449**
* `eval_loss` with `predict_with_generate` TRN: **10.5498**
* `rouge1/2/L/Lsum`: TRN: **0.0**

### TP=1, num workers=2
* `eval_loss` without `predict_with_generate` TRN: 2.4662
* `eval_loss` with `predict_with_generate` TRN: **6.1191**
* `rougeL`: TRN: **22.7219**

**Comment by bocchris-aws** [comment]
Note, `use_cache` has to be set to `False`.

**Comment by michaelbenayoun** [comment]
Can you try to see if this error is fixed using the `main` branch?
