### ISSUE TITLE
LLaMa 2 training with examples/tutorials

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#283]
LLaMa 2 is highly requested by customers. Can we ensure we have LLaMa 2 fine-tuning working with neuronx-distributed including sample code and tutorials for the 7B, 13B and 70B models ?

**Comment by rgrandhiamzn** [comment]
Specifically for Llama-2-7B can we have one with TP and Zero-1. similar to the one in Neuron tutorials but we need a corresponding optimum-neuron version.

 https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/tutorials/training_llama2_7b.html#llama2-7b-tp-zero1-tutorial.

**Comment by rgrandhiamzn** [comment]
Tutorial for Llama-2-70B Training using (TP+PP)
