### ISSUE TITLE
Stable Diffusion examples/tutorials

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#286]
There are no Stable Diffusion examples or tutorials for 1.5, 2.1 or SDXL

**Comment by JingyaHuang** [comment]
Hi @mmcclean-aws , in our documentation, we offered a guide with code snippets and examples for both SD and SDXL models. 
https://huggingface.co/docs/optimum-neuron/guides/models#stable-diffusion
Do the tutorials you mention here refer to a notebook-like guide?
pinging @philschmid, are you preparing something as well?

**Comment by philschmid** [comment]
Yes, working on a SageMaker example.

**Comment by mmcclean-aws** [comment]
@JingyaHuang these are great examples. Perhaps they should go in the tutorial section rather than the heading **Neuron models for inference** whereas we need a specific section calling out Stable Diffusion tutorial/example

**Comment by rgrandhiamzn** [comment]
Can we have an SD inference tutorial with and with out sagemaker. 
 For the one without sagemaker, can it be for SD model. (NeuronStableDiffusionPipeline) where customer can compile/export a model and then loads a model and then does sample inference.

**Comment by JingyaHuang** [comment]
What do you think about Matt's suggestion about moving SD related doc to the tutorial section? I agree that we should probably place SD related doc under the same section instead of mixing with other nlp models. @philschmid

**Comment by kamranjkhan** [comment]
Agree with moving them to their own tutorial section would be better than where they are currently are. Can you also include ready to run examples for each model on github, similar to the sdxl [one](https://github.com/philschmid/huggingface-inferentia2-samples/blob/main/stable-diffusion-xl/sagemaker-notebook.ipynb) just published?

**Comment by rgrandhiamzn** [comment]
Yes, moving those to separate tutorial would be better, can we make the tutorial end-to-end , similar to the published blog.  While the blog focused on sagemaker, this tutorial can be stand alone running on inf2/trn1.

**Comment by philschmid** [comment]
@JingyaHuang having a clear end-to-end documentation/guide for SD/SD XL sounds good to me. It might be easier to find for customer.

**Comment by JingyaHuang** [comment]
Sounds good folks, so I will:
* For `optimum-neuron` documentation, migrate the [SD related examples](https://huggingface.co/docs/optimum-neuron/guides/models#stable-diffusion) from `How-to Guides` to `Tutorials` .
* Create separate notebooks for SD and SDXL for different tasks and put them under [optimum-neuron's github repo](https://github.com/JingyaHuang/optimum-neuron/tree/main/notebooks)

I will make a PR today and tag you all for review, thx.

**Comment by JingyaHuang** [comment]
Hi @rgrandhiamzn @mmcclean-aws @kamranjkhan, SD related doc migration and notebooks are added in the PR #312, could you take a look?
