### ISSUE TITLE
TGI with LLaMa 2 example/tutorial

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#287]
We require sample code and tutorial for running LLaMa 2 with TGI

**Comment by dacorvo** [comment]
I included a dedicated tutorial in the following pull-request: https://github.com/huggingface/optimum-neuron/pull/321

**Comment by philschmid** [comment]
Lets work on this once the container is available for SageMaker or through the marketplace.

**Comment by dacorvo** [comment]
I think this is covered by our blog post. @philschmid ?
