### ISSUE TITLE
Llama 2 inference tutorial

### ISSUE THREAD

**Issue by rgrandhiamzn** [huggingface/optimum-neuron#295]
Llama-2-13b or Llama-2-7b inference tutorial with optimum-neuron similar to the notebook we have for Llama-2-13b

https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/meta-llama-2-13b-sampling.ipynb

**Comment by dacorvo** [comment]
Here is the corresponding pull-request: https://github.com/huggingface/optimum-neuron/pull/300

**Comment by dacorvo** [comment]
Also available as a tutorial in this pull-request: https://github.com/huggingface/optimum-neuron/pull/321
