### ISSUE TITLE
Support for T5-3b inference through NeuronX Distributed

### ISSUE THREAD

**Issue by rgrandhiamzn** [huggingface/optimum-neuron#304]
Support for T5-3b inference through NeuronX Distributed

**Comment by JingyaHuang** [comment]
The task is segmented into 2 parts:
* As the first step, building up the basic modeling for sequence-to-sequence models which enables inference without parallelism: #267 
* 2nd step, plug in parallelism support in `neuronx-distributed`, will open a PR as soon as we get the 1st step into the main branch.
