### ISSUE TITLE
Issue compiling with single Neuron core - no mark_step executed in training loop

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#310]
When attempting to use Optimum Neuron for a single core there is an issue that there is no `xm.mark_step()` executed so many graphs are created for a model when compilation runs. Currently there needs to be at least 2 Neuron Cores running to properly compile a model

**Comment by JingyaHuang** [comment]
I met the same issue before, a workaround would be setting up the `logging_steps` to evoke `xm.mark_step()`. 

https://github.com/huggingface/optimum-neuron/blob/6ed2ecae6023afcf0f8fd99a90ac3c5ba70a86d9/optimum/neuron/trainers.py#L312-L316

@michaelbenayoun shall have more ideas, and I would be happy to help on this topic as well.

**Comment by michaelbenayoun** [comment]
Yes, I gave a quick fix to @mmcclean-aws offline. 
It's a very minor issue I will try to solve this week.
