### ISSUE TITLE
Support for T5-11b T5-XXL + TP

### ISSUE THREAD

**Issue by samir-souza** [huggingface/optimum-neuron#317]
[The XXL version of the model](https://huggingface.co/google/flan-t5-xxl) for Inference is being asked by many customers. Given the size of the model, only through TP it would be possible to load the model.

**Comment by michaelbenayoun** [comment]
It's in the roadmap: #267 will add general support for export and inference using `neuronx_distributed` and we will add support for TP in next PRs.

**Comment by JingyaHuang** [comment]
T5 with TP support is not supported yet, I'm still waiting for the help from the Annapurna team on the issue https://github.com/aws-neuron/aws-neuron-sdk/issues/851
