### ISSUE TITLE
AttributeError: Pipeline object has no attribute 'maybe_free_model_hooks'

### ISSUE THREAD

**Issue by Cerrix** [huggingface/optimum-neuron#327]
Hi, 
I'm using optimum-neuron with Stable Diffusion XL both Text to Image and Image to Image. 
I succeeded in using the `NeuronStableDiffusionXLPipeline` without any issue, but when I use `NeuronStableDiffusionXLImg2ImgPipeline` with SDXL Refiner compiled for neuron I get the following AttributeError: "AttributeError: 'NeuronStableDiffusionXLImg2ImgPipeline' object has no attribute 'maybe_free_model_hooks'" at line: [...]/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_xl_img2img.py:510. 

I searched for it in the repository and the method `maybe_free_model_hooks()` is called 3 times in:
- optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_inpaint.py:392
- [optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_x|_img2img.py:510](https://github.com/huggingface/optimum-neuron/blame/fb283d74310b573116312de993106964437a1595/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_xl_img2img.py#L510) (the pipeline of my error)
- optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_x|_inpaint.py:568
<img width="1110" alt="Screenshot 2023-11-16 at 10 13 42" src="https://github.com/huggingface/optimum-neuron/assets/7694393/924baa10-4286-4167-a00a-026fe667dc0d">

and indeed, `maybe_free_model_hooks()` is not defined in any file. I think that a workaround is maybe remove these lines, but since they were added I would like to understand better if I'm doing something wrong or this method is still to be defined.

This was added in the following merge: #239.

Thank you in advance for the help.

**Comment by Cerrix** [comment]
This was added in the following merge: #239.

**Comment by Cerrix** [comment]
The following seems to be the definition used in Diffuser for the funciton in pipelines utils: https://github.com/huggingface/diffusers/blob/038b42db942e724c86ede866465048fd57e08ee2/src/diffusers/pipelines/pipeline_utils.py#L1458C2-L1458C2

**Comment by Cerrix** [comment]
[update] I commented out the https://github.com/huggingface/optimum-neuron/blame/fb283d74310b573116312de993106964437a1595/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_xl_img2img.py#L510 and now the model is working correctly

**Comment by JingyaHuang** [comment]
Good catch, thanks @Cerrix for reporting this! `maybe_free_model_hooks` is definitely not applicable to neuron, I forgot to remove it when adapting the pipeline from diffuers to optimum-neuron... 

Thanks for reporting it! Since it's your observation, would you like to make a quick PR and tag me for review?

**Comment by Cerrix** [comment]
Yep it would be a pleasure to make the quick PR and make a contribution to this incredible project! 😄

**Comment by JingyaHuang** [comment]
Btw, @Cerrix which version of diffusers library do you use? As this bug was not caught by our CIs which uses v0.23.0.

**Comment by Cerrix** [comment]
@JingyaHuang I'm using the one present in https://aws.amazon.com/marketplace/pp/prodview-gr3e6yiscria2! Let me check 😊

**Comment by JingyaHuang** [comment]
Thanks @Cerrix ! 

I see, the version 0.20.0 of diffusers doesn't have `maybe_free_model_hooks` implemented, that's why it was bugged and not caught by our CIs (in fact the function is a no-op in optimum-neuron). Kudos for catching it!

**Comment by Cerrix** [comment]
Ouch! So it was only a matter of updating my packages! That you so much!

**Comment by JingyaHuang** [comment]
It's great that you spot this, it's definitely better to remove them as they are not for neuron. 

I just merged the PR, thank you again for catching this bug escaped from the CIs check and fix it!

**Comment by Cerrix** [comment]
No problem! Thank you so much for the quick responses (let me thank you again also for this amazing tool!)
