### ISSUE TITLE
What does run_qa.py use tensor or data  parallelism?

### ISSUE THREAD

**Issue by Anand1405** [huggingface/optimum-neuron#334]
I am using optimum neuron run_qa.py to fine-tune GPT2, by looking at the output it seems like it does data parallelism.
Kindly confirm what kind of parallelism is done?
If I enter 8 as batch size it shows total batch size as 16 as I am using it in trn1.2xlarge, so does this mean it is using data parallelism?
If it is data parallelism then how to shift to tensor parallelism?
Also can we use it for trn1.32xlarge with the utilisation of all cores?

**Comment by michaelbenayoun** [comment]
Hi @Anand1405 ,

Yes, by default it does data parallelism. If you use 32 workers on a `trn1.32xlarge` instance, you will be able to use all the cores as well.

Tensor parallelism is supported, but not for GPT-2. We support it for `GPTNeo`, `GPTNeoX` and `LLama` (v1 and v2).

**Comment by Anand1405** [comment]
How do I use tensor parallelism for the same task if I switch to gpt-neo, as by default it does data parallelism?

**Comment by michaelbenayoun** [comment]
I am writing the doc here: #339 .

**Comment by michaelbenayoun** [comment]
Can you share the command line please?
