### ISSUE TITLE
Automated updating of Optimum Neuron hub cache model artifacts

### ISSUE THREAD

**Issue by 5cp** [huggingface/optimum-neuron#342]
Hub cache artifacts for the most popular models/configs should be automatically updated with each Neuron release.

**Comment by dacorvo** [comment]
We already have the [cache script](https://github.com/huggingface/optimum-neuron/blob/main/tools/auto_fill_inference_cache.py) and selected [configs](https://huggingface.co/aws-neuron/optimum-neuron-cache/tree/main/inference-cache-config).
We need to set-up a cluster of servers to run the scripts on the configs when a new version of `optimum-neuron` is released. @5cp @philschmid any idea ?
