### ISSUE TITLE
Expand automated testing to include combinatorial model/config testing for most popular models

### ISSUE THREAD

**Issue by 5cp** [huggingface/optimum-neuron#343]
It's not clear which specific models and configurations are currently tested with each Optimum Neuron and Neuron SDK release. This can leave room for performance/functionality regressions and lack of clarity around what features are supported for each model, etc.

**Comment by michaelbenayoun** [comment]
We have:

- The `tests/test_examples.py` tests with an associated workflow that it is possible to trigger manually. It allows you to test any supported model for training with the all the supported options (ZeRO-1, TP, etc).
- The `tests/distributed/test_model_parallelization.py` that checks that every model that supported model parallelism, can be parallelized properly.
