### ISSUE TITLE
mistral neuron compiler

### ISSUE THREAD

**Issue by jmparejaz** [huggingface/optimum-neuron#356]
Hi I have been following up the last PR over the mistral branch. Just a couple hours ago the branch was merged with main. However, after updating the optimum-neuron to the last version 0.0.15.dev0 and running this code for compiling:

```
from optimum.neuron import NeuronModelForCausalLM
from transformers import AutoTokenizer
#
# # model id you want to compile
#finetuned mistral model with peft QLoRa
vanilla_model_id = "growth-cadet/mistral-7b-news-to-JSON02" 
#
# # configs for compiling model
compiler_args = {"num_cores": 2, "auto_cast_type": "bf16"}
input_shapes = {
   "sequence_length": 2048, # max length to generate
   "batch_size": 1 # batch size for the model
   }
#
llm = NeuronModelForCausalLM.from_pretrained(vanilla_model_id, export=True, **input_shapes, **compiler_args)
tokenizer = AutoTokenizer.from_pretrained(model_id)
#
# # Save locally or upload to the HuggingFace Hub
save_directory = "llama_neuron"
llm.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)
```
I got this error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 13
      8 input_shapes = {
      9    "sequence_length": 2048, # max length to generate
     10    "batch_size": 1 # batch size for the model
     11    }
     12 #
---> 13 llm = NeuronModelForCausalLM.from_pretrained(vanilla_model_id, export=True, **input_shapes, **compiler_args)
     14 tokenizer = AutoTokenizer.from_pretrained(model_id)
     15 #
     16 # # Save locally or upload to the HuggingFace Hub

File /usr/local/lib/python3.8/dist-packages/optimum/modeling_base.py:372, in OptimizedModel.from_pretrained(cls, model_id, export, force_download, use_auth_token, cache_dir, subfolder, config, local_files_only, trust_remote_code, revision, **kwargs)
    369     trust_remote_code = False
    371 from_pretrained_method = cls._from_transformers if export else cls._from_pretrained
--> 372 return from_pretrained_method(
    373     model_id=model_id,
    374     config=config,
    375     revision=revision,
    376     cache_dir=cache_dir,
    377     force_download=force_download,
    378     use_auth_token=use_auth_token,
    379     subfolder=subfolder,
    380     local_files_only=local_files_only,
    381     trust_remote_code=trust_remote_code,
    382     **kwargs,
    383 )

File /usr/local/lib/python3.8/dist-packages/optimum/neuron/modeling_decoder.py:155, in NeuronDecoderModel._from_transformers(cls, model_id, config, use_auth_token, revision, force_download, cache_dir, subfolder, local_files_only, trust_remote_code, task, batch_size, sequence_length, num_cores, auto_cast_type, **kwargs)
    144 # Update the config
    145 config.neuron = {
    146     "task": task,
    147     "batch_size": batch_size,
   (...)
    152     "compiler_version": get_neuronxcc_version(),
    153 }
--> 155 return cls._from_pretrained(checkpoint_dir, config)

File /usr/local/lib/python3.8/dist-packages/optimum/neuron/modeling_decoder.py:205, in NeuronDecoderModel._from_pretrained(cls, model_id, config, use_auth_token, **kwargs)
    201 auto_cast_type = neuron_config["auto_cast_type"]
    203 check_compiler_compatibility(neuron_config["compiler_type"], neuron_config["compiler_version"])
--> 205 exporter = get_exporter(config, task)
    207 model_path, checkpoint_path, compiled_path = cls._get_neuron_paths(model_id, use_auth_token)
    209 # transformers-neuronx uses f32/f16 instead of fp32/fp16

File /usr/local/lib/python3.8/dist-packages/optimum/neuron/modeling_decoder.py:49, in get_exporter(config, task)
     48 def get_exporter(config, task):
---> 49     return TasksManager.get_exporter_config_constructor(model_type=config.model_type, exporter="neuron", task=task)()

File /usr/local/lib/python3.8/dist-packages/optimum/exporters/tasks.py:1807, in TasksManager.get_exporter_config_constructor(exporter, model, task, model_type, model_name, exporter_config_kwargs)
   1804     model_type = model_type.replace("_", "-")
   1805     model_name = getattr(model, "name", model_name)
-> 1807 model_tasks = TasksManager.get_supported_tasks_for_model_type(model_type, exporter, model_name=model_name)
   1809 if task not in model_tasks:
   1810     synonyms = TasksManager.synonyms_for_task(task)

File /usr/local/lib/python3.8/dist-packages/optimum/exporters/tasks.py:1101, in TasksManager.get_supported_tasks_for_model_type(model_type, exporter, model_name)
   1095     raise KeyError(
   1096         f"{model_type_and_model_name} is not supported yet. "
   1097         f"Only {list(TasksManager._SUPPORTED_MODEL_TYPE.keys())} are supported. "
   1098         f"If you want to support {model_type} please propose a PR or open up an issue."
   1099     )
   1100 elif exporter not in TasksManager._SUPPORTED_MODEL_TYPE[model_type]:
-> 1101     raise KeyError(
   1102         f"{model_type_and_model_name} is not supported yet with the {exporter} backend. "
   1103         f"Only {list(TasksManager._SUPPORTED_MODEL_TYPE[model_type].keys())} are supported. "
   1104         f"If you want to support {exporter} please propose a PR or open up an issue."
   1105     )
   1106 else:
   1107     return TasksManager._SUPPORTED_MODEL_TYPE[model_type][exporter]

KeyError: 'mistral is not supported yet with the neuron backend. Only [] are supported. If you want to support neuron please propose a PR or open up an issue.'

**Comment by michaelbenayoun** [comment]
Hi @jmparejaz ,

Yes this is expected. We do not support inference for now, just training. Inference should come soon. cc @JingyaHuang

**Comment by abhijithnair1** [comment]
@michaelbenayoun @JingyaHuang Is there any update on exporting the Mistral 7B to neuron format for inference on inf2 machine?

I wanted to deploy Mistrak 7B model using neuron TGI (https://github.com/huggingface/optimum-neuron/tree/main/text-generation-inference), but if exporting is not supported then I am stuck.

**Comment by jmparejaz** [comment]
is this issue already solved??

**Comment by jimburtoft** [comment]
@abhijithnair1 You can use Mistral on inf2, just not with Optimum yet.  Check out https://huggingface.co/aws-neuron/Mistral-neuron

**Comment by dacorvo** [comment]
Mistral is supported in `optimum-neuron 0.0.17`.
