### ISSUE TITLE
push_to_hub leads to HfHubHTTPError

### ISSUE THREAD

**Issue by harpone** [huggingface/optimum-neuron#358]
I've used `NeuronModelForCausalLM` to load and export Llama-2-7b-hf model, and now trying to push it to HF hub.

I noticed that for some reason, all the weights get dumped to a separate file, which results in a lot of files. This in turn results in `HfHubHTTPError: 429 Client Error: Too Many Requests for url...` which is a bit nasty. I guess I could just wait an hour and try again, but is there any workaround for this? I'd prefer to preserve the Llama-2-7b-hf parameter shards...

**Comment by dacorvo** [comment]
This is a known issue, reported here: https://github.com/huggingface/optimum-neuron/issues/311

We are working with AWS to address this: https://github.com/aws-neuron/transformers-neuronx/issues/57.

**Comment by harpone** [comment]
Ah OK thanks, closing due to duplicate issue (though I still think my issue is more appropriately named :joy: )
