### ISSUE TITLE
SDXL lora on inf2

### ISSUE THREAD

**Issue by MrD005** [huggingface/optimum-neuron#359]
want to implement LoRA on SDXL model on inf2. Is there any support or process to implement this ?

**Comment by JingyaHuang** [comment]
Hi @MrD005,

Thanks for opening the issue, and the contribution is very welcomed!

To support LoRA, the first thing we need to check is whether the neuron compiler support the compilation of text encoder / unet loaded with LoRA weight (theorectically yes). 

To do so, we can do a quick hack:

* Load the LoRA weight to component models in the pipeline before the compilation before this line
https://github.com/huggingface/optimum-neuron/blob/e9c2a9f742fb7e67846b1572291e74e28b2894c3/optimum/exporters/neuron/utils.py#L163

with for example

```python
pipeline.load_lora_weights("ostris/super-cereal-sdxl-lora", weight_name="cereal_box_sdxl_v1.safetensors")
```

If the model compiled successfully, and doesn't meet any issue during the inference, then we can add offically support to the exporter:
* Add a flag like `"--lora_weight"` in `optimum/commands/export/neuronx.py` for supporting it in optimum CLI
* Add lora info to [`main_export`](https://github.com/huggingface/optimum-neuron/blob/e9c2a9f742fb7e67846b1572291e74e28b2894c3/optimum/exporters/neuron/__main__.py#L176) throught the argument `submodels`
* Load the LoRA weight through the function `replace_stable_diffusion_submodels`
https://github.com/huggingface/optimum-neuron/blob/e9c2a9f742fb7e67846b1572291e74e28b2894c3/optimum/exporters/neuron/utils.py#L329

Then we are normally all set, the compiled artifacts should contain the LoRA weights and there is nothing else to add during the inference. 

Much appreciation if you would like to work on it 🙏 . Feel free to ping me for review or any further question!

**Comment by Dev-hestabit** [comment]
Thanks @JingyaHuang i will implement this and revert back if its works or not

**Comment by MrD005** [comment]
Thanks @JingyaHuang  i will implement this and revert back if its works or not

**Comment by khurramkhalil** [comment]
Hi there,
Just wanting to know if there is any update on adding LORAs support on inf2?
Thanks

**Comment by JingyaHuang** [comment]
Hi @khurramkhalil, it's already supported through this PR: https://github.com/huggingface/optimum-neuron/pull/483.

You could also find an example here: https://huggingface.co/docs/optimum-neuron/en/tutorials/stable_diffusion#load-adapters

**Comment by khurramkhalil** [comment]
Thank you very much.
