### ISSUE TITLE
Neuron `consolidate` is not creating `model.safetensors.index.json`

### ISSUE THREAD

**Issue by philschmid** [huggingface/optimum-neuron#367]
When training a model with TP, weights are saved as sharded TP weights. This means we need to consolidate/convert them into regular weights using `optimum neuron consolidate` command. But the command currently is not creating the correct structure. It only saves the `model-00001-of-00002.safetensors` and misses the `model.safetensors.index.json`. 

Additionally we should also copy the `config.json` to the target directory if available. Since it is also always needed to run the model. 

![Bildschirmfoto 2023-12-07 um 13 55 28](https://github.com/huggingface/optimum-neuron/assets/32632186/25f3bfb5-5394-443c-a1fe-a73c0153f4cb)

**Comment by philschmid** [comment]
## Addition: 

It seems the `model.safetensors.index.json` is being created but at the wrong level, when using. 
```bash
optimum-cli neuron consolidate dolly_llama_sharded/tensor_parallel_shards dolly_llama_sharded
```

the `model.safetensors.index.json` is added at `../dolly_llama_sharded` but should be in `dolly_llama_sharded` next to the weights. 

![Bildschirmfoto 2023-12-07 um 14 05 34](https://github.com/huggingface/optimum-neuron/assets/32632186/8f7da7e3-cb6b-4bab-888b-36b1eecc488e)

**Comment by 5cp** [comment]
This small change appears to resolve the issue
```diff
diff --git a/optimum/neuron/distributed/checkpointing.py b/optimum/neuron/distributed/checkpointing.py
index 58a11f8..9fcb986 100644
--- a/optimum/neuron/distributed/checkpointing.py
+++ b/optimum/neuron/distributed/checkpointing.py
@@ -15,6 +15,7 @@
 """Functions handling checkpointing under parallel settings."""

 import json
+import os
 from pathlib import Path
 from typing import Dict, Literal, Union

@@ -95,6 +96,6 @@ def consolidate_tensor_parallel_checkpoints_to_unified_checkpoint(
             torch.save(shard, output_dir / shard_file)
     if index is not None:
         save_index_file = SAFE_WEIGHTS_INDEX_NAME if save_format == "safetensors" else WEIGHTS_INDEX_NAME
-        with open(save_index_file, "w") as fp:
+        with open(os.path.join(output_dir, save_index_file), "w") as fp:
             content = json.dumps(index, indent=2, sort_keys=True) + "\n"
             fp.write(content)
```
