### ISSUE TITLE
SDXL: `neuron_config` of `text_encoder_2` is `CLIPTextNeuronConfig` instead of `CLIPTextWithProjectionNeuronConfig`

### ISSUE THREAD

**Issue by neo** [huggingface/optimum-neuron#371]
I tried to search in the codebase and am not sure how they got chosen, but it appears that `pipeline.text_encoder_2.neuron_config` is `optimum.exporters.neuron.model_configs.CLIPTextNeuronConfig` while I suspect it should be `CLIPTextWithProjectionNeuronConfig`

**Comment by neo** [comment]
wondering is this at least verified that it exists?

**Comment by neo** [comment]
not stale? @JingyaHuang

**Comment by JingyaHuang** [comment]
Will check! Sorry for the late reply.

**Comment by JingyaHuang** [comment]
I kinda got where this question comes from, there is a bug on sdxl when we reconstruct neuron config of text encoder 2 from a json file 😅. The test I did above was during the export, but not the neuron config we reconstructed during the inference:

https://github.com/huggingface/optimum-neuron/blob/3359516a49e2c0c68e3db28d35ece53f38193439/optimum/neuron/modeling_diffusion.py#L524

**Comment by neo** [comment]
hi! yes!

I was going to reply similar _just now_ 😂 I was looking at during loading/inference, and here's what I got:

![image](https://github.com/huggingface/optimum-neuron/assets/9028430/74a09157-56fc-4ab9-b111-777d1dd390d6)

**Comment by neo** [comment]
I also have a feeling that the json file of text encoder 2 might be mistaken too:

https://huggingface.co/aws-neuron/stable-diffusion-xl-base-1-0-1024x1024/blob/main/text_encoder_2/config.json#L30-L34

the text encoder 2 output should include `pooler_output` based on my shallow understanding?

**Comment by JingyaHuang** [comment]
From transformers' clip modeling code, text encoder (`CLIPTextModel`) shall be the one which [has `pooler_output` as output](https://github.com/huggingface/transformers/blob/37fa1f654f17b68bbe30440c64e611f1a4d55bc7/src/transformers/models/clip/modeling_clip.py#L753) while text encoder 2 (`CLIPTextModelWithProjection`) [outputs `text_embeds`](https://github.com/huggingface/transformers/blob/37fa1f654f17b68bbe30440c64e611f1a4d55bc7/src/transformers/models/clip/modeling_clip.py#L1238) which is the text emb obtained by applying the projection layer to the pooled output.

**Comment by neo** [comment]
you're right 😅 I had it the other way around

what I was trying to say is that the two jsons should look different in terms of the neuron. output_names?

or in my case, the `text_encoder.neuron_config.outputs`

**Comment by neo** [comment]
should be fixed by #581
