### ISSUE TITLE
Is Stable Video supported?

### ISSUE THREAD

**Issue by satsumas** [huggingface/optimum-neuron#376]
I'm trying to compile stable video for neuron, using:

```
optimum-cli export neuron -m stabilityai/stable-video-diffusion-img2vid-xt 
stable_video_turbo \
--batch_size 1 --height 512 --width 512  \
--auto_cast matmul --auto_cast_type bf16
```

optimum-cli is complaining that it can't find a tokenizer, and sure enough there is no tokenizer subdir in the Huggingface repo. 

```
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'tokenizer', 'image_encoder', 'unet', 'vae', 'text_encoder', 'safety_checker', 'feature_extractor', 'scheduler'}, but only {'image_encoder', 'unet', 'vae', 'feature_extractor', 'scheduler'} were passed.
```

The model weights `svd.safetensors` are sufficient to run the model in https://github.com/Stability-AI/generative-models, as suggested by the model card. So there are no missing model weights in the repository.  Is there a workaround to this compiler error?

**Comment by satsumas** [comment]
Retrying this compilation using the version of optimum-neuron built from source (`optimum-neuron @ git+https://github.com/huggingface/optimum-neuron.git@f2537d2ccb0ede387518e78e44ed6e0f7976b385`), there is a similar error: 

```
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'feature_extractor', 'vae', 'safety_checker', 'image_encoder', 'scheduler', 'text_encoder', 'tokenizer', 'unet'}, but only {'feature_extractor', 'vae', 'image_encoder', 'scheduler', 'unet'} were passed.
```

**Comment by JingyaHuang** [comment]
Hi @satsumas, the stable video diffusion is not yet supported in optimum-neuron. I am adding the support for exporting image encoder and the neuron version of `StableVideoDiffusionPipeline` in Optimum-neuron. I will keep you posted.

**Comment by satsumas** [comment]
Thank you, that would be great.

**Comment by qingyuan18** [comment]
> Hi @satsumas, the stable video diffusion is not yet supported in optimum-neuron. I am adding the support for exporting image encoder and the neuron version of `StableVideoDiffusionPipeline` in Optimum-neuron. I will keep you posted.

I'm also interested in this new feature for SVD model on Inf2,  is there any approximately release date？ just roughly would be great

Thanks a lot!

**Comment by qingyuan18** [comment]
@satsumas 
hello satsumas 
 any update for the diffuser svd's neuron compile&inference?

**Comment by satsumas** [comment]
Hey @qingyuan18,

I believe we don't have SVD compiled for inf2 with optimum-neuron. You could try compiling it yourself with Inferentia's own neuronx compiler:
 https://awsdocs-neuron.readthedocs-hosted.com/en/latest/compiler/neuronx-cc/api-reference-guide/neuron-compiler-cli-reference-guide.html
