### ISSUE TITLE
No compiler_workdir option in training example to persist Neuron compiler artifacts

### ISSUE THREAD

**Issue by kct22aws** [huggingface/optimum-neuron#379]
I need to profile model compiled by Neuron compiler. This requires access to compiler artifacts such as NEFF. There is no known way to designate compiler_workdir option in ON training example such as [image classification]( https://github.com/huggingface/optimum-neuron/blob/main/examples/image-classification/run_image_classification.py)

**Comment by michaelbenayoun** [comment]
By default it should be `/var/tmp/neuron-compile-cache`.
