### ISSUE TITLE
Inf1 inference test failures

### ISSUE THREAD

**Issue by musunita** [huggingface/optimum-neuron#383]
**INF1 Test Summary:**
* Total Test Passed: 227
* Errors : 9

= 227 passed, 200 skipped, 248 deselected, 47195 warnings, 9 errors in 7509.34s (2:05:09

Test Steps :

-  Setup the neuron environment for your new release
 Setup optimum environment -pip install optimum-neuron

-  Install the latest release: 2.16
Install the dev branch: pip3 install git+https://github.com/huggingface/optimum-neuron#egg=optimum-neuron[tests] tokenizers==0.14.1
-  clone optimum-neuron repo for tests
git clone https://github.com/huggingface/optimum-neuron.git
cd optimum-neuron/
- Run test
 pytest -m is_inferentia_test tests

Config: Inf1.6xlarge tests

Release version:
neuron-cc 1.21.0.0+6cae3b7b8
neuronperf 1.8.15.0+5dccae385
optimum-neuron 0.0.16.dev0
torch-neuron 1.13.1.2.9.17.0

**9 of Testcases have errors:**

NeuronModelIntegrationTest::test_load_model_from_cache
NeuronModelIntegrationTest::test_load_model_from_empty_cache
NeuronModelIntegrationTest::test_load_model_from_hub
NeuronModelIntegrationTest::test_load_model_from_hub_subfolder
NeuronModelIntegrationTest::test_load_model_from_hub_subfolder
NeuronModelIntegrationTest::test_load_model_from_local_path
NeuronModelIntegrationTest::test_save_compiler_intermediary_files
NeuronModelIntegrationTest::test_save_model
NeuronModelIntegrationTest::test_trust_remote_code

Error logs:
```
RuntimeError: Please specify the token via the HF_TOKEN_OPTIMUM_NEURON_CI environment variable
```

Attached complete logs for the failures:
[inf1_on_test_results.txt](https://github.com/huggingface/optimum-neuron/files/13688134/inf1_on_test_results.txt)

**Comment by JingyaHuang** [comment]
Hi @musunita , all these hub integration tests need a huggingface token. If you are running it locally, you can export a dummy HF token as env variable to run the test.

**Comment by musunita** [comment]
Can you clarify, how do you export dummy HF token as env variable ?

**Comment by jeffhataws** [comment]
Setup account to get token here: https://huggingface.co/docs/huggingface_hub/quick-start#authentication

**Comment by JingyaHuang** [comment]
Hi folks, is the token issue solved? May I close this issue? @musunita @jeffhataws

**Comment by jeffhataws** [comment]
Let's close this for now. Will open new one if there are issues.
