### ISSUE TITLE
Mixtral 8x7B Instruct support

### ISSUE THREAD

**Issue by Prasanna-iq** [huggingface/optimum-neuron#394]
Hi, 
when can we expect the support for Mixtral 8x7B ?
I can see Mistral 7B is not supported yet. 
Thanks

**Comment by jimburtoft** [comment]
@Prasanna-iq optimum-neuron supports Mistral for training.  If you want to do inference on Inferentia/Trainium, check out https://huggingface.co/aws-neuron/Mistral-neuron

For Mixtral, this project needs Mixtral support in [transformer-neuronx](https://github.com/aws-neuron/transformers-neuronx), which is almost there.

**Comment by davidshtian** [comment]
As newly launched Neuron SDK 2.18 has supported [Mixtral 8x7B model](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/documentation/neuron-documentation.html?highlight=mixtral#neuron-2-18-0) (transformer_neuronx has supported [this](https://github.com/aws-neuron/transformers-neuronx/tree/main/src/transformers_neuronx/mixtral)). It would be great to have this feature added in Optimum Neuron. Thanks~ 🚀

**Comment by PhilipMay** [comment]
Is there a timeline when the Mixtral support will be added?

**Comment by PhilipMay** [comment]
> This is already merged on main if you want to give it a try. It should be included in the next release.

So this issue can be closed?

**Comment by dacorvo** [comment]
Mixtral is supported since 0.0.22.
