### ISSUE TITLE
add epfLLM/meditron-7b and epfLLM/meditron-70b to model cache

### ISSUE THREAD

**Issue by yyz-selfiie** [huggingface/optimum-neuron#396]
Please add the two models trained on top of llama2, epfLLM/meditron-7b and epfLLM/meditron-70b, to model cache.

https://github.com/epfLLM/meditron
https://huggingface.co/epfl-llm/meditron-7b
https://huggingface.co/epfl-llm/meditron-70b

Thanks.

**Comment by dacorvo** [comment]
These models don't seem to be among the most popular LLama variants for which we provide cached versions.
I f you think there should be cached anyway, feel free to open a cache request in https://huggingface.co/aws-neuron/optimum-neuron-cache with rationale.
