### ISSUE TITLE
Request to support ESM

### ISSUE THREAD

**Issue by JacobLenzing** [huggingface/optimum-neuron#400]
Will support be added to run ESM2 on inf2. I am currently not able to compile the model [https://huggingface.co/facebook/esm2_t33_650M_UR50D](url) 

Any help is appreciated!

**Comment by JingyaHuang** [comment]
Hi @JacobLenzing, thanks for raising the request. For which tasks would you want to add the support? Would it be a task with esm2 as encoder or decoder?

**Comment by JacobLenzing** [comment]
Hi @JingyaHuang thank you for answering. I would like to use it for sequence encoding. Maybe also decoding at some point:)

Is this a possibility?

**Comment by JingyaHuang** [comment]
Hi @JacobLenzing, sure the support of ESM as an encoder should be pretty straightforward (decoder could be a little bit tricky as I don't think it's supported in transformers so far).

I want to take this opportunity to set a guide for community members when they want to add support for a new model type, could you check out the pull request that I opened #446 in which I created:

* [Guide to add ESM](https://moon-ci-docs.huggingface.co/docs/optimum-neuron/pr_461/en/community/contributing)
* And an example of the Neuron config for ESM:
https://github.com/huggingface/optimum-neuron/blob/989e7173b8a2b94cb32905a9bf5121060d9c0126/optimum/exporters/neuron/model_configs.py#L105-L111

Would you like to follow the guide, open a pull request, and contribute ESM to Optimum Neuron? If you have any suggestions to the guide documentation, it will be as precious as gold, thx 🤗 !

**Comment by JingyaHuang** [comment]
ESM is now supported by optimum-neuron through #461 .
