### ISSUE TITLE
Test if `optimum-cli neuron cache add` works. 

### ISSUE THREAD

**Issue by michaelbenayoun** [huggingface/optimum-neuron#404]
As per title. From tests it might appear that nothing is pushed. To investigate.

**Comment by jimburtoft** [comment]
@michaelbenayoun I've been using `optimum-cli neuron cache synchronize` with no problems other than an initial permission issue with the cache on HF.

**Comment by michaelbenayoun** [comment]
It's not for the same purpose, the `add` command is for training. We are investigating if both will be merged at some point.
