### ISSUE TITLE
Migrate Hugging Face DLAMI into optimum neuron

### ISSUE THREAD

**Issue by philschmid** [huggingface/optimum-neuron#433]
We want to migrate the code and infrastructure from [Hugging Face Deep Learning AMI (DLAMI)](https://aws.amazon.com/marketplace/pp/prodview-gr3e6yiscria2) to the Optimum Neuron repository to have a more transparent view for customers, a unified repository and CI integration for tests and releases. 
We want to make improvements to the existing DLAMI, including: 

## Items

* [x] Try to use the official PyTorch DLAMI as base image. (Try to see if those can be automatically derived `aws ec2 describe-images --region us-east-1 --owners amazon --filters 'Name=name,Values=Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04) ????????' 'Name=state,Values=available' --query 'reverse(sort_by(Images, &CreationDate))[:1].ImageId' --output text`)
* [x] Make sure we use the ubuntu as user to install packages (currently sudo)
* [x] Fix the `apt get` issue https://github.com/huggingface/optimum-neuron/issues/270
* [x] Migrate [IaC code](https://github.com/huggingface/aws-neuron-internal) to the optimum repository.
* [ ] Add CI (Github Actions) integration. We want to run automated tests every 1-2 days to build the AMI and run tests to make sure everything works as expected. The CI should use the "main" branch from optimum and send a notification if failed. We also want a pipeline that can easily build a new "production" image using the latest versions, which we can then publish. 
* [x] Also add [notebooks](https://github.com/huggingface/optimum-neuron/tree/main/notebooks) into the AMI 

## Considerations

While looking into how to pass parameters to the EC2 Image builder and how to use a "user" account, i noticed that it might be easier to move to [packer](https://developer.hashicorp.com/packer/tutorials/aws-get-started/aws-get-started-build-image), which could directly run in the GitHub Actions. This could allow us to pass parameters into the image-building pipeline more easily. Please validate the consideration.

**Comment by shub-kris** [comment]
I am taking it up.
