### ISSUE TITLE
TGI for Inf2 returns the input text even if return_full_text is set to False

### ISSUE THREAD

**Issue by tahirazim** [huggingface/optimum-neuron#436]
As of https://github.com/huggingface/optimum-neuron/commit/3b3afa4dad427c0d43d3c799431a0e2619ac636a, calling a TGI endpoint for Inf2 returns the input text even if `return_full_text` is set to False in the request. 

This is not the case for regular TGI.

**Comment by philschmid** [comment]
@tahirazim is fixed in 0.0.18
