### ISSUE TITLE
TGI for Inf2 does not special=True in the last token of a stream

### ISSUE THREAD

**Issue by tahirazim** [huggingface/optimum-neuron#437]
As of https://github.com/huggingface/optimum-neuron/commit/3b3afa4dad427c0d43d3c799431a0e2619ac636a, when calling a TGI endpoint for Inf2, it does not set `special=True` in the last token of a stream. As a result, callers have to guess the end of the stream based on an assumption of what the last token will be.

Here is an example last token I get from the TGI endpoint:

```
data:{"token":{"id":2,"text":"</s>","logprob":0.0,"special":false},"generated_text":"/inf2 How are you?\n\nI'm doing well, thanks for asking! I'm always happy to chat with you and help with any questions or topics you'd like to discuss. How about we talk about something you're interested in or passionate about?</s>","details":null}

```

Note that this is not the case for regular TGI.

**Comment by dacorvo** [comment]
This should be fixed in https://github.com/huggingface/optimum-neuron/pull/438. Thank you for reporting the error !
