### ISSUE TITLE
Error `export` when output already exists. 

### ISSUE THREAD

**Issue by philschmid** [huggingface/optimum-neuron#444]
I am compiling some models with different configs using the optimum-cli. I noticed that when you specify an output which already exists it will error at the end after compiling, which is a bit painful, e.g. for Llama or Mistral. Lets add a check in the beginning
```bash
FileExistsError: [Errno 17] File exists: 'zephyr-7b-beta-neuron/checkpoint'
```

**Comment by dacorvo** [comment]
Fixed in 0.0.18
