### ISSUE TITLE
Neuron export -> import `num_cores` 

### ISSUE THREAD

**Issue by michaelfeil** [huggingface/optimum-neuron#464]
https://huggingface.co/gradientai/v-alpha-tross/commit/6774b0d59761aa072e9e96132838873ce692a1a3

huggingface 01232024 ami (the latest one) on inf2.x48large

https://huggingface.co/gradientai/v-alpha-tross/commit/6774b0d59761aa072e9e96132838873ce692a1a3

```python
from optimum.neuron import NeuronModelForCausalLM

compiler_args = {"num_cores": 24, "auto_cast_type": 'bf16'}
input_shapes = {"batch_size": 1, "sequence_length": 2048}
model = NeuronModelForCausalLM.from_pretrained(
        "gradientai/v-alpha-tross",
        export=True,
        **compiler_args,
        **input_shapes)

model.save_pretrained("./compiled/alphatross")

model.push_to_hub(
    "./compiled/alphatross"
    "gradientai/v-alpha-tross-neuron"
)
```

```python
model = NeuronModelForCausalLM.from_pretrained(
        "gradientai/v-alpha-tross-neuron",
        **compiler_args,
        **input_shapes)
```

I get `TypeError: __init__() got an unexpected keyword argument 'num_cores'.`

 I think you changed num_cores to tp_degree

**Comment by michaelfeil** [comment]
nevermind, I forgot to set `        export=True` in the bottomo statement.

**Comment by dacorvo** [comment]
You can only specify the number of cores during export: afterwards it is read back from the model configuration as it corresponds to the compiled graphs.
