### ISSUE TITLE
Support compilation on any instance, not just inf/trn

### ISSUE THREAD

**Issue by thesyntaxinator** [huggingface/optimum-neuron#493]
### Feature request

Officially AWS says you can compile to Neuron using any instance type or onprem and they recommend a c5 or z1d instance for large models. Being able to use optimum neuron to compile on any instance (not just inf or trn) would similarly allow users to compile large models more easily.

### Motivation

Officially AWS says you can compile to Neuron using any instance type or onprem and they recommend a c5 or z1d instance for large models. Being able to use optimum neuron to compile on any instance (not just inf or trn) would similarly allow users to compile large models more easily.

### Your contribution

I can test

**Comment by JingyaHuang** [comment]
Hi @thesyntaxinator, you can compile models on CPU-only instances by turning off the validation (inference needs to be done on Neuron devices) using `--disable-validation` with the CLI. More details [here](https://huggingface.co/docs/optimum-neuron/en/guides/export_model#:~:text=by%20Neuronx%20compiler.-,%2D%2Ddisable%2Dvalidation,-Whether%20to%20disable).
