### ISSUE TITLE
Add support for phi-2

### ISSUE THREAD

**Issue by 5cp** [huggingface/optimum-neuron#508]
### Feature request

phi-2 is one of the most popular models and should be supported by Optimum Neuron. I was able to trace the model using torch_neuronx.trace() using a slightly modified version of the [BERT tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/torch-neuronx/bert-base-cased-finetuned-mrpc-inference-on-trn1-tutorial.html) and did not encounter any errors:

```
2024-03-07T05:44:03Z Compiler status PASS

CPU paraphrase logits: [[-1.0661223 0.8461684]]
Neuron paraphrase logits: [[-1.0701762 0.8514435]]
CPU not-paraphrase logits: [[-1.111944 0.84410715]]
Neuron not-paraphrase logits: [[-1.1247162 0.8532015]]
```

### Motivation

phi-2 was identified as one of the top models. It has also been requested by end users.

### Your contribution

Confirmed that model can be traced by Neuron as-is.

**Comment by JingyaHuang** [comment]
Hi @5cp, I will open a PR to add support for phi family models on the following tasks: feature-extraction, text-classification, token-classification.

For the causal task, I wonder if phi is supported by `transformers_neuronx` @dacorvo.

**Comment by dacorvo** [comment]
@JingyaHuang no, it is not supported.
