### ISSUE TITLE
Muti Node CLM Mistral training tutorial

### ISSUE THREAD

**Issue by shamanez** [huggingface/optimum-neuron#511]
### Feature request

Similar to neuronx_distributed, can we have a tutorial on how to use multi-node with optimum neuron. 

### Motivation

Having multi-node capabilities will make the training process much more efficient. 

### Your contribution

Can help with debugging.

**Comment by dacorvo** [comment]
cc @michaelbenayoun @philschmid

**Comment by michaelbenayoun** [comment]
I will work on that. I think we can improve the tutorial we have on the doc a lot. I plan to this.
