### ISSUE TITLE
Add batch size and sequence length compile options to config

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#53]
When compiling a model with `optimum-cli export neuron` it would be useful to store the compiled model batch size and sequence length values so that the inference server can use this information when creating the tokenizer for inference requests

**Comment by philschmid** [comment]
Yes totally agree @JingyaHuang I thought we are saving the information inside the `config.json` already.

**Comment by JingyaHuang** [comment]
Hi @mmcclean-aws, thanks for the suggestion, it makes total sense. 

@philschmid, no, it is not yet the case. I wanted to setup a separate config purely for neuron related in coming PR(namly the one of modeling). As we discussed last time, now I'll just store it into transformers' config.

A PR is opened here to enhance the export: #55

**Comment by JingyaHuang** [comment]
It shall looks like this:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/44135271/235665061-09f31b75-2c4b-4c8b-9173-3484fccd0cdb.png">
WDYT? @philschmid @mmcclean-aws

**Comment by philschmid** [comment]
Looks good!
