### ISSUE TITLE
Add optimum-neuron support for diffusers.StableDiffusionControlNetPipeline

### ISSUE THREAD

**Issue by yahavb** [huggingface/optimum-neuron#575]
### Feature request

Implement ControlNet in Neuron to control stable diffusion image generation with control image condition like in https://huggingface.co/docs/diffusers/en/api/pipelines/controlnet#diffusers.StableDiffusionControlNetPipeline.__call__.example

### Motivation

flexible and accurate way to control the image generation process on AWS Inferentia instances 

### Your contribution

Happy to contribute test scripts and documentation.

**Comment by asutermo** [comment]
Any update on this?

**Comment by yahavb** [comment]
We still need that indeed.
