### ISSUE TITLE
Error message trying to publish model to aws-neuron/optimum-neuron repo when training a model

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#59]
When performing the training of a model and using the default settings with the compilation cache, at the end of the training run the script attempts to push the model to the repo `aws-neuron/optimum-neuron` which the user only has ready access to. There are multiple error messages similar to the following:

```
Repository Not Found for url: https://huggingface.co/api/models/aws-neuron/optimum-neuron-cache/preupload/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
Note: Creating a commit assumes that the repo already exists on the Huggingface Hub. Please use `create_repo` if it's not the case..
Could not push the cached model to the repo aws-neuron/optimum-neuron-cache, most likely due to not having the write permission for this repo. Exact error: 401 Client Error. (Request ID: Root=1-64552cae-2d7d62ab5b517ed01749d20b)
```

Would be good to avoid trying to push to this particular repo but give an informational message that users can push to their own repo.

**Comment by michaelbenayoun** [comment]
Should be fixed by #71.
Please re-open this PR if the issue reappears.
