### ISSUE TITLE
convert llama model with text-genertaion type into inferentia compatible modle

### ISSUE THREAD

**Issue by PierrePeng** [huggingface/optimum-neuron#62]
Following this [tutorial](https://huggingface.co/docs/optimum-neuron/guides/export_model), I encounter this error "**llama is not supported yet with the neuron backend. Only [] are supported. If you want to support neuron please propose a PR or open up an issue.**" after running "optimum-cli export neuron" command.

**Comment by JingyaHuang** [comment]
Hi @PierrePeng, thanks for the feedback!

llama is not supported in optimum-neuron yet. You can find out all supported model architectures [here](https://moon-ci-docs.huggingface.co/docs/optimum-neuron/pr_65/en/package_reference/configuration#supported-architectures). 

We are actively adding more supported architectures, including decoders like Llama, stay tuned!

**Comment by PierrePeng** [comment]
> 

Thanks bro.
