### ISSUE TITLE
optimum_cli:main doesn't exist in the latest version of the code. 

### ISSUE THREAD

**Issue by mccartni-aws** [huggingface/optimum-neuron#623]
### System Info

```shell
https://github.com/huggingface/optimum-neuron/blob/af0506f2aa1200c3580fe0506ad27598132d7e85/setup.py#L105

This line references a function call that doesn't exist.
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

1. Clone the repo (v0.0.23, done on 5th June) and install using 
```
git clone https://github.com/huggingface/optimum-neuron.git
cd optimum-neuron
python setup.py install
```
2. Run `optimum-cli export neuron`

3. See error: 
```
usage: optimum-cli export [-h] {onnx,tflite} ...
optimum-cli export: error: argument {onnx,tflite}: invalid choice: 'neuron' (choose from 'onnx', 'tflite')
```

### Expected behavior

I should be prompted for a model (or any of the other required flags for exporting a neuron model.

**Comment by hthrrr** [comment]
hey, how did you fix this at the end? im having the same problem
