### ISSUE TITLE
Support for model compiltion/exportation on non-Neuron hardware.

### ISSUE THREAD

**Issue by mccartni-aws** [huggingface/optimum-neuron#626]
### Feature request

Please make it more obvious to the user that compilation & exportation of models has to be done on Neuron hardware

Please put this statement "An important restriction is that LLM models can only be exported on Neuron platforms, as they are tailored to fit on the actual devices during export." somewhere 'higher up' in the repo documentation, so users don't waste time experimenting with these commands on non-inferentia hardware. 

 https://github.com/huggingface/optimum-neuron/blob/af0506f2aa1200c3580fe0506ad27598132d7e85/docs/source/guides/export_model.mdx 
 

### Motivation

Given that most AWS users have to submit a quota increase request for inf1 and inf2 instances in the first place, they should be made aware that they're going to need to be compiling and exporting models on the Neuron hardware. 

inf2 instances can only be deployed as endpoint in most European AWS regions, meaning there is a real barrier for entry for most of these users as they can't easily spin up inf2 EC2 instances with :/ 

### Your contribution

I am happy to thoroughly test and participate in Quality Assurance for a new solution that allows compilation/exportation on non-neuron hardware.

**Comment by dacorvo** [comment]
Thank you for your feedback.
Only LLMs need to be exported on Neuron platforms. This is why it is only mentioned in the LLM export paragraph.
If you feel this should be mentioned higher in that paragraph, please submit a pull-request with a suggested change.
