### ISSUE TITLE
Failing image modeling tests

### ISSUE THREAD

**Issue by dacorvo** [huggingface/optimum-neuron#689]
### System Info

```shell
inferentia2 ubuntu 22.04 host, AWS Neuron SDK 2.19.1, optimum-neuron main
```

### Who can help?

@JingyaHuang 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Some image modeling tests are failing since the update to latest transformers version.

For instance:

```python
tests/inference/test_modeling.py::NeuronModelForImageClassificationIntegrationTest::test_pipeline_model - ValueError: Attempting to cast a BatchFeature to type None. This is not supported.
```

### Expected behavior

All modeling test should pass without errors.

**Comment by JingyaHuang** [comment]
The CIs are all green now, will close this.
